### ISSUE TITLE
Incorrect state date written by rvn_rvt_write

### ISSUE THREAD

**Issue by nickyrong** [rchlumsk/RavenR#100]
I have a xts time series (SCK_flow) for observed flow. First time stamp = 2014-09-05.

After I write the rvt file with rvn_rvt_write() function, the initial time was output incorrectly:

rvn_rvt_write(x = SCK_flow,
              rvt_type = "ObservationData",
              data_type = "HYDROGRAPH",
              basin_ID = 1,
              filename = "../2_Input_files/SCK_ObservedFlows.rvt")

And this is what's in the .rvt file, the month is wrong

:ObservationData HYDROGRAPH 1 m3/s
   2014-**00**-05 00:00:00 1 1510
  0.567142
  0.563274

**Comment by rchlumsk** [comment]
Hi Nick

Thanks for finding this bug and reporting it. The culprit was a %M instead of %m in a line that reformats the date time, resulting in the hour being written in instead of the month. This is now fixed in the last push to the dev branch.

Thanks again,
Rob
