### ISSUE TITLE
add function to run Raven system command

### ISSUE THREAD

**Issue by rchlumsk** [rchlumsk/RavenR#13]
Want to run Raven from within R using a path to Raven.exe and the system command, to work cross-platform.

Update the examples to use all Nith model files to run Raven for the Nith basin within this package.

**Comment by analytophile** [comment]
Since it is just a shell command, do you need to be able to do this as a separate ravenR routine?

**Comment by rchlumsk** [comment]
Fair point, we can leave this out for now as it likely would not add much benefit
