### ISSUE TITLE
update themes and colour schemes for all ggplot functions

### ISSUE THREAD

**Issue by rchlumsk** [rchlumsk/RavenR#14]
Come up with a coherent colour wheel and theme to apply to all ggplot graphics across the package, and implement in code.

**Comment by scantle** [comment]
I often use the Tableau 10 and Tableau 20 palettes, they're not perfect but it can be a real hassle to find that many distinct colors!
Here's those, and a bunch more: https://jrnold.github.io/ggthemes/reference/tableau_color_pal.html

**Comment by rchlumsk** [comment]
Updated R/rvn_theme_RavenR by @sgrass91 addresses this, may still update the colours used and other formatting as needed
