### ISSUE TITLE
Check and cleanup rvt functions and other Raven reading/writing functions

### ISSUE THREAD

**Issue by rchlumsk** [rchlumsk/RavenR#17]
Check and cleanup rvt functions and other Raven reading/writing functions

Some new rvt functions, for example, use the tidyhydat and weathercan packages to supply input for writing rvt files. Not sure if having other versions of input is worthwhile for this. Review and comment on the reading/writing functions.

**Comment by scantle** [comment]
rvn_ECmet_rvt had some conflicting lines of code and didn't run as intended, I have made the follows changes on my fork:
- changed to accept tibble from weathercan::weather_dl(), or dataframe with same data (e.g., read in from a csv file later)
- uses RavenR's rvn_write_rvt function to generate the rvt files
- made prefix an optional character argument (default: met_)
- station/redirect filenames now optional arguments
- spaces in station names are replaced with underscores

New suggested workflow (see example in file) is to download using weather_dl() and then pass to rvn_ECmet_rvt

I'm also working on some minor related upgrades to rvn_write_rvt while I work through this task.

**Comment by scantle** [comment]
rvn_tidyhydat_rvt runs fine. Minor changes:
 - redirect filename now an optional argument
 - minor changes to documentation & example

This function has arguments with underscores, rvn_ECmet_rvt used periods. Are we standardizing towards underscores? Also do we need a generic RVT writing function for gauges instead of met data?

**Comment by rchlumsk** [comment]
Yes, we should change the functions to use underscores instead of periods in the syntax where possible.

On the second question, something that writes out the gauge data in rvt format to a file based on the metadata provided from the stations_search function directly would be helpful. Something like: 

weathercan::stations_search("Waterloo", interval="day") %>% 
  filter(station_id %in% c(4832, 4831)) %>%
  rvn_rvt_write_gauge(.)

Final comment, the functions related to rvt are hard to find based on name. Perhaps a standard should be to have the rvt/rvi/ etc file type first, then the action. Then anything rvt related could be found by RavenR::rvn_rvt_*

This would rename, for example, rvn_ECmet_rvt to rvn_rvt_ECmet_write (or just rvn_rvt_ECmet), or similar.

**Comment by scantle** [comment]
> Yes, we should change the functions to use underscores instead of periods in the syntax where possible.

Done

> the functions related to rvt are hard to find based on name. Perhaps a standard should be to have the rvt/rvi/ etc file type first, then the action. Then anything rvt related could be found by RavenR::rvn_rvt_*

I have moved rvt in front of the data source for both functions I was working on.

> On the second question, something that writes out the gauge data in rvt format to a file based on the metadata provided from the stations_search function directly would be helpful. 

I created a new function for this purpose, **rvn_rvt_ECmet_fromStns()**:
```
weathercan::stations_search("Waterloo", interval="day") %>%
            filter(station_id %in% c(4831, 4832)) %>%
            rvn_rvt_ECmet_fromStns(start="1970-10-01", end="1980-09-30", interval="day")
```
I also updated rvn_rvh_write() and added new functions to return blank SubBasin and HRU tables for use with it (useful for getting all the column names right). Example:
```
#-- Create RVH tables
sbs_data <- rvn_rvh_blankSBdf()
hru_data <- rvn_rvh_blankHRUdf(nHRUs = 3)

#-- Fill in HRU data
hru_data$Area <- round(HRU_shp$Area / (1000^2),3)  # m2 to km2

# ETC #

#-- Write RVH file
rvn_rvh_write('ScriptOut/BigHead.rvh',
              SBtable = sbs_data,
              HRUtable = hru_data,
              description = 'BigHead River Raven RVH file generated by GenRVNfiles.R',
              author = 'Leland Scantlebury')
```
