### ISSUE TITLE
Addition of Nith River HRU shapefile to package library

### ISSUE THREAD

**Issue by aviolinist** [rchlumsk/RavenR#32]
This is required for the `rvn_gen_gridweights.R` example, which uses grid and HRU shapefiles as part of the function inputs to generate an .rvi file of grid weights for the basin.

Grid shapefile is generated by passing Nith.nc into `rvn_netcdf_to_gridshp.R`, which currently has external package dependencies that are not yet compatible with R 4.0+. Requires follow-up.

The example workflow for `rvn_gen_gridweights.R` (revised by SL, 2020-07-23) is shown below:
```
#'   # Example workflow
#'   # load example rvh file
#'   nith <- system.file("extdata",'Nith.rvh', package = "RavenR")
#'   rvh <- rvn_rvh_read(nith)
#'
#'   # define HRU shapefiles (needs to be added to library)
#'   HRUshpfile <- system.file("extdata","Nith_HRU.shp",package = "RavenR")
#'
#'   # write grid shapefile from netcdf file
#'   nithnc <- system.file("extdata","Nith.nc",package = "RavenR")
#'   GridCells <- "Nith_GridCells.shp"
#'   UTMzone <- 17
#'   GRDshpfile <- rvn_netcdf_to_gridshp(nithnc,UTMzone,GridCells)
#'
#'   # generate .rvi file of grid weights
#'   validHRUIDs <- rvh$HRUtable$ID
#'   tmp <- rvn_gen_gridweights(HRUshpfile, GRDshpfile, validHRUIDs,
#'    gridIDcol = 'GridIDs', HRUIDcol = "HRU_ID", outfile = "Nith_GridWeights.rvi)
```

**Comment by rchlumsk** [comment]
Updated the example for this function to use the existing subbasin shapefile and updating Nith rvh HRU table to just one for each subbasin. 

Getting the full HRU shapefile would still be helpful.

**Comment by rchlumsk** [comment]
Closing as spatial functions have been since removed from RavenR package
