### ISSUE TITLE
rvn_rvt_ECmet

### ISSUE THREAD

**Issue by rchlumsk** [rchlumsk/RavenR#45]
Change default filename writing to have rvt extension but not in file name

Currently writes out: 
"station_name.rvt.rvt"

**Comment by scantle** [comment]
@rchlumsk another issue with this function, while we're at it - the snowfall data is in **solid** cm, which needs to be converted to mm, but also needs a density correction to SWE mm. If you look at an ECmet data total precip column you'll see they assume 1 cm snow = 1 mm SWE (10% density). Either we should assume the same or have an argument for it.
In other words, right now we're adding in ~10x the correct amount of water through the snowfall data!

**Comment by scantle** [comment]
In my fork, I opted for having `rvn_rvt_write()` check if the extension already was present before adding it:
```
  #-- Correct file extension if not included
  if (rvn_substrRight(ff,4) != ".rvt") {
    ff <- paste0(ff,".rvt")
  }
```

**Comment by rchlumsk** [comment]
One more item here, having forcing_set be defined as either a pre-determined number (easy sets to use) or specified columns from the forcing sets (i.e. c("temp_max","temp_min") ) would be great.
