### ISSUE TITLE
Feature request - convert subbasin and hru shp files to Raven format tables

### ISSUE THREAD

**Issue by rchlumsk** [rchlumsk/RavenR#47]
Something that looks for subbasin id, downstream id, aspect, length, etc and grabs the information from shp (as sf) or other formats into the Raven formats. Options to specify the column name or index number from the sf or data frame or matric=x

**Comment by scantle** [comment]
I have some code to do this that I'll rework to be more generic. It might not be everything you envisioned but can serve as a starting point.

**Comment by rchlumsk** [comment]
That would be great even as a starting point. If you put it into a pull request to the dev branch I am happy to get it further generalized down the road.
