### ISSUE TITLE
rvn_custom_read stores numeric values as characters

### ISSUE THREAD

**Issue by scantle** [rchlumsk/RavenR#59]
rvn_custom_read incorrectly returns an xts object with all data stored as characters.

Seems to be related to the xts object being passed the time column as a data column.

**Comment by rchlumsk** [comment]
Does this happen with the package built in data set or another set? I haven't noticed this but should be fixed asap

**Comment by scantle** [comment]
This happens when I read in custom data sets I recently produced - they include a "hour" column _not_ present in the built-in custom data set. Maybe a recent change in Raven? Maybe @analytophile can weigh in.

I was working on a fix that handled date/time columns more like we do in rvn_hyd_read().

**Comment by scantle** [comment]
I dug into the Raven source code, and the "hour" column is only included when output is written for every timestep (e.g. CONTINUOUS in the custom output).

I'd say the correct fix is to check for an hourly column and handle if present.
