### ISSUE TITLE
rvn_rvt_ECmet with generic writing of forcings

### ISSUE THREAD

**Issue by rchlumsk** [rchlumsk/RavenR#63]
the function currently only allows for 2 forcing sets in determining which forcings can be written. A generic mapping of input data to Raven forcing types, as well as allowing the user to specify which forcings they want written to the rvt file (e.g. forcings_written =c("temp_daily_max", "snowfall") ) would be ideal to avoid a very large set of prescribed forcing sets

The common forcing sets are perhaps still helpful, or perhaps a default set as c("total_precip", "temp_daily_min","temp_daily_max") is sufficient.

Variable names for forcings should correspond to those produced by the weathercan package for convenience, but without requiring data from the package explicitly (i.e. jsut expects a data frame with those variable names)

**Comment by scantle** [comment]
In my mind, by default it should write _all_ of the forcings Raven can use. This would support users interested in experimenting with their Raven setup and seeing the effects of including different forcings. Alternatively, perhaps an optional "All" forcing set.

**Comment by drg2314** [comment]
Hey Rob,

I was looking for this issue and had a comment.
For some of the EC sites, there's no precip data available, so it writes a -1.2345 for precip. However, Raven doesn't allow negative or blank precip data I believe. Also, someone might use CAPA for precip + EC for temperature during model calibration. It would be nice to have an option where you can select just the min/max temperatures.

**Comment by rchlumsk** [comment]
Hey Konhee, with some delay this is now addressed. The rvn_rvt_write_met function now writes the rvt file based on whatever data is passed to it, so choosing which forcings to write is a matter of passing the desired forcings in the data set supplied to the function. A couple of additional steps to specify the matching between data-supplied column names and Raven ones, but it is setup to work directly with weathercan based on the default column name mapping.

Closed with new commit to dev branch
