### ISSUE TITLE
request for updating ProcConnTable file in the rvn_rvi_connections

### ISSUE THREAD

**Issue by rarabzad** [rchlumsk/RavenR#82]
The fragmented plots generated by rvn_rvi_process_plot is due to the bad "connection" object inherited from function rvn_rvi_connections. Digging into the rvn_rvi_connections, sounds that it is working properly in terms of comparing the user-selected algorithms in the rvi file. However, for process algorithms not found in the processes master file (ProcConnTable), but recognizable by Raven, the rvn_rvi_connections will skip those algorithms and apparently will be omitted in the connections object.

**Comment by rarabzad** [comment]
Working on it to update the dat file and probably the plot function will work afterward

**Comment by rchlumsk** [comment]
Fixed in latest commit, add in #88 - thanks Rezgar!
