### ISSUE TITLE
rvn_rvi_read: error in the evaluation of conditional statement

### ISSUE THREAD

**Issue by rarabzad** [rchlumsk/RavenR#89]
For a sample model calibration input files (example C4) on Raven webpage, the function reports an error about evaluation of an conditional statement where FALSE/TRUE needed

**Comment by rchlumsk** [comment]
Thanks for this - just fixed in the dev branch version of rvn_rvi_read

On line 70 of parsing the file, there is a check for null lines but not zero-length lines. Updated now!
